version: "3.1"

services:
  graphicalservices-app:
    image: graphical-services-backend
    
    env_file:
      - .env
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080

    # volumes:
    #   - .:/app/
    #   - /app/node_modules