export { default as downarrow } from './downarrow.svg';
export { default as mainLogo } from './graphical-logo.png';
export { default as mainLogoWhite } from './graphical-logo-white.png';
export { default as machine } from './Image-homepage.jpg';
export { default as libras } from './libras.png';
export { default as instagram } from './instagram.png';
export { default as google } from './google.png';
export { default as whatsapp } from './whatsapp.png';
export { default as facebook } from './facebook.png';
export { default as gmail } from './gmail.png';
export { default as apple } from './apple.png'
export { default as signLanguageIcon} from './libras.png';
export { default as darkThemeIcon} from './dark-theme.svg';
export { default as lensDown} from './lensDown.svg';
export { default as lensUp} from './lensUp.svg';
export { default as accessIcon} from './accessIcon.svg';
export { default as plastificadora} from './plastificadora.jpeg';
export { default as impresoraOffset} from './impresora_offset.jpg';
export { default as troquel} from './troquel.jpeg';
export { default as disenador} from './disenadora-grafica-ordenador.jpg';
export { default as agenda} from './agenda.jpg';
export { default as caja} from './caja.png';
export { default as cajaTorta} from './caja_torta.png';
export { default as baseTorta} from './base_torta.jpg';
export { default as search} from './magnifying-glass-search.png';